name: Code Scan
description: Run security repo precommit scan on push
inputs:
  upstreamRepoUrl:
    description: 'Upstream Repo'
    required: true
  upstreamBranch:
    description: 'Upstream Repo branch'
    required: true
runs:
    using: composite
    steps:
        - run: echo "git remote add upstream ${{inputs.upstreamRepoUrl}}"
          shell: bash
        - run: echo "git pull upstream ${{inputs.upstreamBranch}}"
          shell: bash
        - run: git remote -v
          shell: bash
