name: Code Scan
description: Run security repo precommit scan on push
inputs:
  upstream-repo-url:
    description: 'Upstream Repo'
    required: true
  upstream-branch:
    description: 'Upstream Repo's branch'
    required: true
runs:
    using: composite
    steps:
        - run: git remote add upstream ${{upstream-repo-url}} ${{upstream-branch}}
          shell: bash
        - run: git remote -v
          shell: bash
