name: Code Scan
description: Run security repo precommit scan on push
inputs:
  upstreamRepoUrl:
    description: 'Upstream Repo'
    required: true
  upstreamBranch:
    description: 'Upstream Repo branch'
    required: true
runs:
    using: composite
    steps:
        - run: set -o xtrace
          shell: bash
        - run: git remote add upstream $INPUT_UPSTREAMREPOURL
          shell: bash
        - run: git pull upstream $INPUT_UPSTREAMBRANCH
          shell: bash
        - run: git remote -v
          shell: bash
