name: Code Scan
description: Run security repo precommit scan on push
inputs:
  upstream-repo-url:
    description: 'Upstream Repo'
    required: true
  upstream-branch:
    description: 'Upstream Repo branch'
    required: true
runs:
    using: composite
    steps:
        - run echo $INPUT_UPSTREAM-REPO-URL
          shell: bash
        - run: git remote add upstream $INPUT_UPSTREAM-REPO-URL
          shell: bash
        - run: git pull upstream $INPUT_UPSTREAM-BRANCH
          shell: bash
        - run: git remote -v
          shell: bash
