name: Code Scan
description: Run security repo precommit scan on push
inputs:
  upstreamRepoUrl:
    description: 'Upstream Repo'
    required: true
  upstreamBranch:
    description: 'Upstream Repo branch'
    required: true
runs:
    using: composite
    steps:
        - run: git remote add upstream ${{inputs.upstreamRepoUrl}}
          shell: bash
        - run: git fetch upstream ${{inputs.upstreamBranch}}
          shell: bash
        - run: git remote -v
          shell: bash
        - run: git reset --hard upstream/master
          shell: bash
        - run: git push origin master --force
          shell: bash
          
